"""create User table

Revision ID: 50eeeebfb73f
Revises:
Create Date: 2021-09-09 18:04:15.172922

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50eeeebfb73f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("account_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(
        op.f("ix_users_account_name"), "users", ["account_name"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_account_name"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
