"""create User table

Revision ID: a14af6cf667e
Revises:
Create Date: 2021-09-09 18:25:17.268639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a14af6cf667e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("account_name", sa.String(length=32), nullable=False),
        sa.Column("hashed_password", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(
        op.f("ix_users_account_name"), "users", ["account_name"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_account_name"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
